name = "lead-api"
main = "src/worker.js"           # o tu ruta real: src/index.ts/js
compatibility_date = "2025-05-20"
workers_dev = true               # sin routes ni custom domains aquí

# ⚠️ IMPORTANTE: NO añadas 'logpush' ni bloques [observability] aquí.

# --- Enlaces/bindings que ya usabas ---
[[d1_databases]]
binding = "DB"
database_name = "legal_leads"    # tu D1
database_id = "REEMPLAZA_CON_TU_ID"

# Si usabas vars públicas (no secretos), puedes declararlas aquí:
  [vars]
 MAIL_PROVIDER = "resend"
 MAIL_FROM = "no-reply@example.com"
 DEFAULT_EMAIL = "leads@example.com"
 ALLOWED_ORIGINS = "https://ismatpg.github.io"
