name = "lead-api"
main = "src/index.js"
compatibility_date = "2024-11-20"
workers_dev = true
migrations_dir = "migrations"

# 🔧 Esto evita que wrangler toque "script-settings" de logs.
[observability]
enabled = false

[vars]
MAIL_PROVIDER   = "resend"
MAIL_FROM       = "no-reply@example.com"
DEFAULT_EMAIL   = "leads@example.com"
ALLOWED_ORIGINS = "https://ismatpg.github.io"

[[d1_databases]]
binding       = "DB"
database_name = "legal_leads"
database_id   = "REPLACE_WITH_YOUR_D1_ID"
