name = "lead-api"
main = "src/index.js"
compatibility_date = "2025-05-20"
workers_dev = true

[observability]
enabled = false  # <- fuerza OFF; evita tocar script-settings


# --- Enlaces/bindings que ya usabas ---
[[d1_databases]]
binding = "DB"
database_name = "database"    # tu D1
database_id = "8879e33a-4762-489e-a61f-9506bf1d97f9"

# Si usabas vars públicas (no secretos), puedes declararlas aquí:
  [vars]
 MAIL_PROVIDER = "resend"
 MAIL_FROM = "no-reply@example.com"
 DEFAULT_EMAIL = "ismael.guijarro.raissouni@gmail.com"
 ALLOWED_ORIGINS = "https://ismatpg.github.io"



